# Generated by Django 4.1.3 on 2023-07-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0004_nodebody_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodebody',
            name='data',
            field=models.JSONField(default=list),
        ),
    ]
