# Generated by Django 4.1.3 on 2023-08-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0006_remove_nodemedia_image_alter_nodemedia_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodemedia',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'not_set'), (2, 'youtube')], default=1, max_length=100),
        ),
    ]
