# Generated by Django 4.1.3 on 2023-08-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0007_alter_nodemedia_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodemedia',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'not_set'), (2, 'youtube')], default=1),
        ),
    ]
