# Generated by Django 4.1.3 on 2022-11-17 13:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0003_nodebody_fields'),
        ('learning_session', '0004_auto_20221117_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlearningsession',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='userlearningsession',
            name='root',
        ),
        migrations.RemoveField(
            model_name='userlearningsession',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userlearningsession',
            name='total_repetitions',
        ),
        migrations.AddField(
            model_name='userlearningsession',
            name='additional_queue',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='userlearningsession',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userlearningsession',
            name='targets',
            field=models.ManyToManyField(default=list, related_name='learning_sessions', to='node.palacenode'),
        ),
        migrations.CreateModel(
            name='LearningSessionStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('repeated_nodes', models.IntegerField(default=0)),
                ('learning_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='learning_session.userlearningsession')),
            ],
        ),
    ]
