# Generated by Django 4.1.3 on 2023-01-20 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_session', '0006_auto_20221129_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningsessionstatistics',
            old_name='repeated_nodes',
            new_name='repetitions',
        ),
    ]
