# Generated by Django 4.1.3 on 2023-07-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_session', '0008_rename_learning_session_learningsessionstatistics_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlearningsession',
            name='queue_generation_strategy',
            field=models.IntegerField(choices=[(2, 'outdated_first'), (1, 'random')], default=2),
        ),
    ]
