# Generated by Django 4.1.3 on 2023-07-23 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_session', '0009_alter_userlearningsession_queue_generation_strategy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlearningsession',
            name='learning_strategy',
        ),
    ]
