# Generated by Django 4.1.3 on 2023-08-10 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0006_remove_nodemedia_image_alter_nodemedia_type'),
        ('learning_session', '0010_remove_userlearningsession_learning_strategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeRepetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repetitions', to='node.palacenode')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repetitions', to='learning_session.userlearningsession')),
            ],
        ),
    ]
