# Generated by Django 4.1.3 on 2023-08-24 00:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0008_alter_nodemedia_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_session', '0013_remove_userlearningsession_repeated_nodes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLearningSession',
            new_name='LearningSession',
        ),
    ]
