# Generated by Django 4.1.3 on 2023-09-03 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_session', '0014_rename_userlearningsession_learningsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningsession',
            name='last_repetition_datetime',
        ),
        migrations.RemoveField(
            model_name='learningsession',
            name='queue',
        ),
        migrations.DeleteModel(
            name='NodeRepetition',
        ),
    ]
