# Generated by Django 4.1.3 on 2023-09-04 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0008_alter_nodemedia_type'),
        ('learning_session', '0015_remove_learningsession_last_repetition_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='current_node',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='node.palacenode'),
        ),
    ]
