# Generated by Django 4.1.3 on 2023-09-04 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0008_alter_nodemedia_type'),
        ('learning_session', '0016_learningsession_current_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeLearningContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_repetition', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node.palacenode')),
            ],
        ),
    ]
