# Generated by Django 4.1.3 on 2023-09-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_session', '0018_alter_nodelearningcontext_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodelearningcontext',
            name='easiness',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
