# Generated by Django 4.1.3 on 2023-09-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_session', '0020_alter_nodelearningcontext_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodelearningcontext',
            name='easiness',
            field=models.DecimalField(decimal_places=2, default=2.6, max_digits=4),
        ),
    ]
