# Generated by Django 4.0.5 on 2022-10-08 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_initial'),
        ('statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodelearningstatistics',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='node.palacenode'),
        ),
    ]
