# Generated by Django 4.1.3 on 2023-09-03 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('node', '0008_alter_nodemedia_type'),
        ('learning_session', '0015_remove_learningsession_last_repetition_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeRepetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repetitions', to='node.palacenode')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repetitions', to='learning_session.learningsession')),
            ],
        ),
    ]
