# Generated by Django 4.1.2 on 2022-10-27 18:15
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlearningsession",
            name="last_repetition_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="userlearningsession",
            name="start_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
