# Generated by Django 4.1.3 on 2022-11-17 13:49

from django.db import migrations


def delete_all_sessions(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    LearningSession = apps.get_model('session', 'UserLearningSession')
    LearningSession.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_alter_userlearningsession_last_repetition_datetime_and_more'),
    ]

    operations = [
        migrations.RunPython(delete_all_sessions),
    ]
